### PR TITLE
#645: Don't remove still used decryptor methods

### LINKED ISSUE #645: Allatori string decryption will fail when encrypted multiple times
Background:
1. Allatori string encryption was applied 3 times (or more).
2. It appears the same method is used multiple times for each decryption function (example provided below).
3. doesn't result in any error.

Consider the following:
We have a standard Allatori decryption call:
`decrypt_method_1("foobar", 1337)`

This is the failure point:
`decrypt_method_1(decrypt_method_2(decrypt_method_1("foobar", 1337), 2555, 4444))`

On each pass, the transformer will remove the decryption method, so when we first decrypt method_1, it will be removed and thus unavailable for the third and final decryption.

I can provide a jar, but not publicly.

### PR DESCRIPTION
**Pull request by Janmm14**
Fixes #645 

Improve allatori string decryption by not removing methods which are still called.

Fixes method removal count as well.

Also some general code style and minor speed improvements.

### CODE REVIEW

File: src/main/java/com/javadeobfuscator/deobfuscator/rules/allatori/RuleStringDecryptor.java [hunk 1]
```diff
@@ -48,44 +49,40 @@ public String test(Deobfuscator deobfuscator) {
...
+                            .filter(mn -> mn.name.equals(m.name) && mn.desc.equals(m.desc))
+                            .findFirst().orElse(null);
+                    if (decryptorNode == null || decryptorNode.instructions == null) {
+                        continue;
+                    }
 
-                            if (!isAllatori) {
-                                continue;
-                            }
+                    if (!com.javadeobfuscator.deobfuscator.transformers.allatori.StringEncryptionTransformer.isAllatoriMethod(decryptorNode)) {
```
Comment (ItzSomebody) [inline src/main/java/com/javadeobfuscator/deobfuscator/rules/allatori/RuleStringDecryptor.java:69]: Perhaps these kinds of methods should be thrown in their own class or something.

File: src/main/java/com/javadeobfuscator/deobfuscator/transformers/allatori/StringEncryptionTransformer.java [hunk 2]
```diff
@@ -25,22 +32,41 @@
...
-import java.util.*;
-import java.util.concurrent.atomic.AtomicInteger;
+public class StringEncryptionTransformer extends Transformer<StringEncryptionTransformer.Config> {
+
+    public static class Config extends TransformerConfig {
+        private boolean cleanup = true;
 
-public class StringEncryptionTransformer extends Transformer<TransformerConfig> {
+        public Config() {
+            super(ConstantFolder.class);
```
Comment (ItzSomebody) [inline src/main/java/com/javadeobfuscator/deobfuscator/transformers/allatori/StringEncryptionTransformer.java:59]: Was this intentional?

Comment (Janmm14) [reply src/main/java/com/javadeobfuscator/deobfuscator/transformers/allatori/StringEncryptionTransformer.java:59]: no

File: src/main/java/com/javadeobfuscator/deobfuscator/rules/allatori/RuleStringDecryptor.java [hunk 3]
```diff
@@ -48,44 +49,40 @@ public String test(Deobfuscator deobfuscator) {
...
-                            isAllatori = isAllatori && TransformerHelper.containsInvokeVirtual(decryptorNode, "java/lang/String", "length", "()I");
-                            isAllatori = isAllatori && TransformerHelper.countOccurencesOf(decryptorNode, IXOR) > 2;
-                            isAllatori = isAllatori && TransformerHelper.countOccurencesOf(decryptorNode, NEWARRAY) > 0;
+                    if (ain.getOpcode() != Opcodes.INVOKESTATIC) {
+                        continue;
+                    }
+                    MethodInsnNode m = (MethodInsnNode) ain;
+                    String strCl = m.owner;
+                    if ((!m.desc.equals("(Ljava/lang/Object;)Ljava/lang/String;") && !m.desc.equals("(Ljava/lang/String;)Ljava/lang/String;"))
+                        || !deobfuscator.getClasses().containsKey(strCl)) {
```
Comment (fee1-dead) [inline src/main/java/com/javadeobfuscator/deobfuscator/rules/allatori/RuleStringDecryptor.java:58]: consider splitting this for better readability

File: src/main/java/com/javadeobfuscator/deobfuscator/transformers/allatori/StringEncryptionTransformer.java [hunk 4]
```diff
@@ -85,114 +110,174 @@ public boolean canCheckEquality(JavaValue first, JavaValue second, Context conte
...
+        isAllatori = isAllatori && map.getOrDefault(CASTORE, zero).get() > 0;
+        isAllatori = isAllatori && map.getOrDefault(NEW, zero).get() > 0;
+        isAllatori = isAllatori && map.getOrDefault(IINC, zero).get() > 0;
+        isAllatori = isAllatori && map.getOrDefault(IXOR, zero).get() > 0;
+        isAllatori = isAllatori && map.getOrDefault(I2C, zero).get() > 0;
+        isAllatori = isAllatori && map.getOrDefault(ARETURN, zero).get() > 0;
+        isAllatori = isAllatori && map.getOrDefault(NEWARRAY, zero).get() == 1;
+        isAllatori = isAllatori && TransformerHelper.containsInvokeVirtual(decryptorNode, "java/lang/String", "charAt", "(I)C");
+        isAllatori = isAllatori && TransformerHelper.containsInvokeVirtual(decryptorNode, "java/lang/String", "length", "()I");
+        isAllatori = isAllatori && TransformerHelper.containsInvokeSpecial(decryptorNode, "java/lang/String", "<init>", null);
```
Comment (fee1-dead) [inline src/main/java/com/javadeobfuscator/deobfuscator/transformers/allatori/StringEncryptionTransformer.java:215]: These statements might be better with a function call `boolean and(boolean... booleans)`

File: src/main/java/com/javadeobfuscator/deobfuscator/transformers/allatori/StringEncryptionTransformer.java [hunk 5]
```diff
@@ -85,114 +110,174 @@ public boolean canCheckEquality(JavaValue first, JavaValue second, Context conte
...
+                    break;
+                }
+            } else if (!getClassName && name.equals("getClassName")) {
+                getClassName = true;
+                if (getStackTrace) {
+                    break;
+                }
+            }
+        }
+        if (!getClassName || !getStackTrace) {
```
Comment (fee1-dead) [inline src/main/java/com/javadeobfuscator/deobfuscator/transformers/allatori/StringEncryptionTransformer.java:239]: Maybe `if (!(getClassName && getStackTrace))`?

File: src/main/java/com/javadeobfuscator/deobfuscator/transformers/allatori/StringEncryptionTransformer.java [hunk 6]
```diff
@@ -85,114 +110,174 @@ public boolean canCheckEquality(JavaValue first, JavaValue second, Context conte
...
+                MethodNode mNode = owner.methods.stream().filter(mn -> mn.name.equals(m.name) && mn.desc.equals(m.desc)).findFirst().orElse(null);
+                toRemove.remove(mNode);
+            }
+        }));
         AtomicInteger count = new AtomicInteger(0);
         classNodes().forEach(classNode -> {
-            if (classNode.methods.removeIf(methods::contains)) {
-                count.getAndIncrement();
+            for (Iterator<MethodNode> it = classNode.methods.iterator(); it.hasNext(); ) {
+                MethodNode methodNode = it.next();
```
Comment (fee1-dead) [inline src/main/java/com/javadeobfuscator/deobfuscator/transformers/allatori/StringEncryptionTransformer.java:276]: Why are you iterating like this

File: src/main/java/com/javadeobfuscator/deobfuscator/utils/TransformerHelper.java [hunk 7]
```diff
@@ -202,6 +229,22 @@ public static int countOccurencesOf(MethodNode methodNode, int opcode) {
         return i;
     }
 
+    public static Map<Integer, AtomicInteger> calcOpcodeOccurenceMap(MethodNode methodNode) {
+        Map<Integer, AtomicInteger> map = new HashMap<>();
+        for (AbstractInsnNode abstractInsnNode : methodNode.instructions) {
+            int opcode = abstractInsnNode.getOpcode();
+            if (opcode >= 0) {
```
Comment (fee1-dead) [inline src/main/java/com/javadeobfuscator/deobfuscator/utils/TransformerHelper.java:236]: When is opcode less than 0? Why should this be a check?

**Review by fee1-dead — CHANGES_REQUESTED** [review]

File: src/main/java/com/javadeobfuscator/deobfuscator/transformers/allatori/StringEncryptionTransformer.java (hunk 6 above)
Comment (Janmm14) [reply src/main/java/com/javadeobfuscator/deobfuscator/transformers/allatori/StringEncryptionTransformer.java:276]: Because I use it.remove()

File: src/main/java/com/javadeobfuscator/deobfuscator/utils/TransformerHelper.java (hunk 7 above)
Comment (Janmm14) [reply src/main/java/com/javadeobfuscator/deobfuscator/utils/TransformerHelper.java:236]: frames and labels have opcode -1

File: src/main/java/com/javadeobfuscator/deobfuscator/transformers/allatori/StringEncryptionTransformer.java (hunk 5 above)
Comment (Janmm14) [reply src/main/java/com/javadeobfuscator/deobfuscator/transformers/allatori/StringEncryptionTransformer.java:239]: I think neither representation is superior to the other, so I don't want to change it

File: src/main/java/com/javadeobfuscator/deobfuscator/transformers/allatori/StringEncryptionTransformer.java (hunk 6 above)
Comment (fee1-dead) [reply src/main/java/com/javadeobfuscator/deobfuscator/transformers/allatori/StringEncryptionTransformer.java:276]: use removeIf?

File: src/main/java/com/javadeobfuscator/deobfuscator/transformers/allatori/StringEncryptionTransformer.java (hunk 4 above)
Comment (Janmm14) [reply src/main/java/com/javadeobfuscator/deobfuscator/transformers/allatori/StringEncryptionTransformer.java:215]: Such a function call would always do every check and not shortcircuit.

Comment (fee1-dead) [reply src/main/java/com/javadeobfuscator/deobfuscator/transformers/allatori/StringEncryptionTransformer.java:215]: But this is still doing every check. `if (!condition) return false;` would be better

Comment (Janmm14) [reply src/main/java/com/javadeobfuscator/deobfuscator/transformers/allatori/StringEncryptionTransformer.java:215]: No its not. Shortcircuit is happening here. It checks isAllatori first, if it is false, it doesn't evaluate the other half, as the result of `&&` is already clear.

File: src/main/java/com/javadeobfuscator/deobfuscator/transformers/allatori/StringEncryptionTransformer.java (hunk 6 above)
Comment (Janmm14) [reply src/main/java/com/javadeobfuscator/deobfuscator/transformers/allatori/StringEncryptionTransformer.java:276]: That was how it worked before, but it did not count correctly. It counted amount of edited classes and not amount of removed methods.

File: src/main/java/com/javadeobfuscator/deobfuscator/transformers/allatori/StringEncryptionTransformer.java (hunk 4 above)
Comment (ItzSomebody) [reply src/main/java/com/javadeobfuscator/deobfuscator/transformers/allatori/StringEncryptionTransformer.java:215]: IMHO, this should be fine as is.

File: src/main/java/com/javadeobfuscator/deobfuscator/utils/TransformerHelper.java (hunk 7 above)
Comment (ItzSomebody) [reply src/main/java/com/javadeobfuscator/deobfuscator/utils/TransformerHelper.java:236]: Hmmm, a possible remedy is to use `Utils.isInstruction(AbstractInsnNode)` which returns true if the list node isn't a line number/frame/label.

File: src/main/java/com/javadeobfuscator/deobfuscator/transformers/allatori/StringEncryptionTransformer.java (hunk 6 above)
Comment (ItzSomebody) [reply src/main/java/com/javadeobfuscator/deobfuscator/transformers/allatori/StringEncryptionTransformer.java:276]: > That was how it worked before, but it did not count correctly. It counted amount of edited classes and not amount of removed methods.

Huh.  I'm honestly not sure why that happens.  Will make a note to look into that at some point.

Comment (Janmm14) [reply src/main/java/com/javadeobfuscator/deobfuscator/transformers/allatori/StringEncryptionTransformer.java:276]: > 
> 
> > That was how it worked before, but it did not count correctly. It counted amount of edited classes and not amount of removed methods.
> 
> Huh. I'm honestly not sure why that happens. Will make a note to look into that at some point.

Uh, isn't that obvious?

The previous code uses classNode.methods.removeIf which returns true if at least one method was removed, and then it increased count by one. The new style increases count every time we remove a method.

Comment (ItzSomebody) [reply src/main/java/com/javadeobfuscator/deobfuscator/transformers/allatori/StringEncryptionTransformer.java:276]: Ah wait, I see.  Yes, it is trivial.  Looks like I was just being 2iq at the time.

**Comment by ItzSomebody** [comment]
@fee1-dead:  Any objections?  If not, I'll merge.

**Comment by Janmm14** [comment]
> 
> 
> @fee1-dead: Any objections? If not, I'll merge.

I'll address https://github.com/java-deobfuscator/deobfuscator/pull/762#discussion_r637383805 tomorrow thne it should be good to go

**Comment by Janmm14** [comment]
Tomorrow got a little delayed.

**Review by fee1-dead — APPROVED** [review]
LGTM
